# Generated by Django 3.2.16 on 2022-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('qte', models.IntegerField()),
                ('dateAjout', models.DateField()),
            ],
        ),
    ]
